- name: Import Management Root Zip File into {{ import_management_root_zip_instance_id }}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.reverse_proxy.management_root.all.import_zip
    isamapi:
      instance_id: "{{ import_management_root_zip_instance_id }}"
      filename   : "{{ import_management_root_zip_filename }}"
  when: import_management_root_zip_filename is defined and import_management_root_zip_instance_id is defined
  notify:
  - Commit Changes
