################# configure_reverseproxy_junctions ##############
instances:
-   inst_name: default
    junctions:
      -   junction_point:             "/jct1"
          junction_type:              "tcp"
          servers:
            -   server_hostname:    "localhost"
                server_port:        443
                

# Default variables for configuration of reverse proxy junctions
#instances: []

#inst_name: "{{ item.inst_name }}"

# Configuration entry to control, if not listed junction servers should be deleted on the server
delete_junction_server: false
delete_junctions: false
force: false


###configure_reverseproxy_instances###

# Default variables for configuration of reverse proxy instances
instances: []

# variables to control whether to configure one instance and/or a specific stanza at a time or everything from the configurations
inst_name: "{{ item.0.inst_name }}"
stanza: "{{ item.1.stanza }}"
entry_name: "{{ item.1.entry_name }}"

# variables to manage trigger action
action_method: "{{ 'set' if item.1.method == 'set' else
                        'add' if item.1.method == 'add' else
                            'delete' if item.1.method == 'delete' else
                                'get'
                }}"

# parameter to be passed to ansible module
action_params:
    set:
        reverseproxy_id: "{{ item.0.inst_name }}"
        stanza_id:       "{{ item.1.stanza }}"
        entries:
                -
                    - "{{ item.1.entry_name }}"
                    - "{{ item.1.value }}"
    add:
        reverseproxy_id: "{{ item.0.inst_name }}"
        stanza_id:       "{{ item.1.stanza }}"
        entries:
                -
                    - "{{ item.1.entry_name }}"
                    - "{{ item.1.value }}"
    delete:
        reverseproxy_id: "{{ item.0.inst_name }}"
        stanza_id:       "{{ item.1.stanza }}"
        entry_id: "{{ item.1.entry_name }}"
        value_id: "{{ item.1.value }}"


 #######jmt files #######################
 # Default variables for uploading jmt files
jmt_files: [file1,file2,file3]


#######runtime_templates #######################
 runtime_templates:
   - id: "server1"
     filename:  "abc.html"
   - id: "server2"
     filename:  "abc2.html"
   - id: "server3"
     filename:  "abc3.html"
   - id: "server4"
     filename:  "abc4.html"

#####################import_management_root_zip_filename #############
import_management_root_zip_filename: /tmp/a.zip
import__management_root_instance_id:
